//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saveimgsvg
    {
        public int ID { get; set; }
        public int CaseNo { get; set; }
        public string svg { get; set; }
    }
}
